# Generated by Django 2.2.5 on 2019-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateField(auto_created=True)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
